DAY15/DAY13_1/Models/Learner.cs
namespace DAY13_1.Models
{
    public class Learner
    {
        public Learner()
        {
            Enrollments = new HashSet<Enrollment>();
        }
        public int LearnerID { get; set; }
        public string LastName { get; set; }
        public string FirstMidName { get; set; }
        public DateTime EnrollmentDate { get; set; }
        public int MajorID { get; set; }
        public virtual Major? Major { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}

DAY15/DAY13_1/Controllers/LearnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAY13_1.Models;

namespace DAY13_1.Controllers
{
    public class LearnersController : Controller
    {
        private readonly SchoolContext _context;

        public LearnersController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Learners


        // GET: Learners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var learner = await _context.Learners
                .Include(l => l.Major)
                .FirstOrDefaultAsync(m => m.LearnerID == id);
            if (learner == null)
            {
                return NotFound();
            }

            return View(learner);
        }

        // GET: Learners/Create
        public IActionResult Create()
        {
            ViewData["MajorID"] = new SelectList(_context.Majors, "MajorID", "MajorID");
            return View();
        }

        // POST: Learners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LearnerID,LastName,FirstMidName,EnrollmentDate,MajorID")] Learner learner)
        {
            if (ModelState.IsValid)
            {
                _context.Add(learner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MajorID"] = new SelectList(_context.Majors, "MajorID", "MajorID", learner.MajorID);
            return View(learner);
        }

        // GET: Learners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var learner = await _context.Learners.FindAsync(id);
            if (learner == null)
            {
                return NotFound();
            }
            ViewData["MajorID"] = new SelectList(_context.Majors, "MajorID", "MajorID", learner.MajorID);
            return View(learner);
        }

        // POST: Learners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LearnerID,LastName,FirstMidName,EnrollmentDate,MajorID")] Learner learner)
        {
            if (id != learner.LearnerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(learner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LearnerExists(learner.LearnerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MajorID"] = new SelectList(_context.Majors, "MajorID", "MajorID", learner.MajorID);
            return View(learner);
        }

        // GET: Learners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var learner = await _context.Learners
                .Include(l => l.Major)
                .FirstOrDefaultAsync(m => m.LearnerID == id);
            if (learner == null)
            {
                return NotFound();
            }

            return View(learner);
        }

        // POST: Learners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var learner = await _context.Learners.FindAsync(id);
            if (learner != null)
            {
                _context.Learners.Remove(learner);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LearnerExists(int id)
        {
            return _context.Learners.Any(e => e.LearnerID == id);
        }
        //khai báo biến toàn cục pageSize
        private int pageSize = 3;

        public IActionResult Index(int? mid)
        {
            var learners = (IQueryable<Learner>)_context.Learners
                .Include(m => m.Major);

            if (mid != null)
            {
                learners = (IQueryable<Learner>)_context.Learners
                    .Where(l => l.MajorID == mid)
                    .Include(m => m.Major);
            }

            //tính số trang
            int pageNum = (int)Math.Ceiling(learners.Count() / (float)pageSize);

            //trả số trang về view để hiển thị nav-trang
            ViewBag.PageNum = pageNum;

            //lấy dữ liệu trang đầu
            var result = learners.Take(pageSize).ToList();

            return View(result);
        }

        public IActionResult LearnerFilter(int? mid, string? keyword, int? pageIndex)
        {
            // Lấy toàn bộ learners trong dbset chuyển về IQuerrable<Learner> để query
            var learners = (IQueryable<Learner>)_context.Learners;

            // Lấy chỉ số trang, nếu chỉ số trang null thì gán ngầm định bằng 1
            int page = (int)(pageIndex == null || pageIndex <= 0 ? 1 : pageIndex);

            // Nếu có mid thì lọc learner theo mid (chuyên ngành)
            if (mid != null)
            {
                // lọc
                learners = learners.Where(l => l.MajorID == mid);
                // Gửi mid về view để ghi lại trên nav-phân trang
                ViewBag.mid = mid;
            }

            // Nếu có keyword thì tìm kiếm theo tên
            if (keyword != null)
            {
                // tìm kiếm
                learners = learners.Where(l => l.FirstMidName.ToLower().Contains(keyword.ToLower()));
                // Gửi keyword về view để ghi trên nav-phân trang
                ViewBag.keyword = keyword;
            }

            // Tính số trang
            int pageNum = (int)Math.Ceiling(learners.Count() / (float)pageSize);

            // Gửi số trang về view để hiển thị nav-trang
            ViewBag.pageNum = pageNum;

            // Chọn dữ liệu trong trang hiện tại
            var result = learners.Skip(pageSize * (page - 1))
                .Take(pageSize)
                .Include(m => m.Major)
                .ToList();

            return PartialView("LearnerTable", result);
        }
        public IActionResult LearnerByMajorID(int mid)
        {
            var learners = _context.Learners
                .Where(l => l.MajorID == mid)
                .Include(m => m.Major).ToList();
            return PartialView("LearnerTable", learners);
        }

     
    }
}

DAY15/DAY13_1/ViewComponent/MajorViewComponent.cs
using DAY13_1.Models;
using Microsoft.AspNetCore.Mvc;

namespace DAY13_1
{
    public class MajorViewComponent : ViewComponent
    {
        SchoolContext db;
        List<Major> majors;

        public MajorViewComponent(SchoolContext _context)
        {
            db = _context;
            majors = db.Majors.ToList();
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("RenderMajor", majors);
        }
    }
}

DAY15/DAY13_1/Views/Learners/Create.cshtml
@model DAY13_1.Models.Learner

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Learner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstMidName" class="control-label"></label>
                <input asp-for="FirstMidName" class="form-control" />
                <span asp-validation-for="FirstMidName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EnrollmentDate" class="control-label"></label>
                <input asp-for="EnrollmentDate" class="form-control" />
                <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MajorID" class="control-label"></label>
                <select asp-for="MajorID" class ="form-control" asp-items="ViewBag.MajorID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DAY15/DAY13_1/Views/Learners/Delete.cshtml
@model DAY13_1.Models.Learner

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Learner</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnrollmentDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Major)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Major.MajorID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LearnerID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DAY15/DAY13_1/Views/Learners/Details.cshtml
@model DAY13_1.Models.Learner

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Learner</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnrollmentDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Major)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Major.MajorID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.LearnerID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DAY15/DAY13_1/Views/Learners/Edit.cshtml
@model DAY13_1.Models.Learner

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Learner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LearnerID" />
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstMidName" class="control-label"></label>
                <input asp-for="FirstMidName" class="form-control" />
                <span asp-validation-for="FirstMidName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EnrollmentDate" class="control-label"></label>
                <input asp-for="EnrollmentDate" class="form-control" />
                <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MajorID" class="control-label"></label>
                <select asp-for="MajorID" class="form-control" asp-items="ViewBag.MajorID"></select>
                <span asp-validation-for="MajorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DAY15/DAY13_1/Views/Learners/Index.cshtml
@model IEnumerable<DAY13_1.Models.Learner>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
@await Component.InvokeAsync("Major");

<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
    <div class="input-group">
        <input id="keyword" class="form-control" name="keyword"
               type="text" placeholder="Search learner" />
        <button id="btnSearch" class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
        </button>
    </div>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div id="content">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Tên
                </th>
                <th>
                    Họ
                </th>
                <th>
                    Ngày nhập học
                </th>
                <th>
                    Chức năng
                </th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LearnerID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstMidName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EnrollmentDate)
                </td>
            
                <td>
                    <a asp-action="Edit" asp-route-id="@item.LearnerID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.LearnerID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.LearnerID">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>
    <ul class="pagination">
        @for (int i = 1; i <= ViewBag.pageNum; i++)
        {
            <li class="page-item" page="@i"
                @(ViewBag.mid != null ? "mid='" + ViewBag.mid + "'" : "")
                @(ViewBag.keyword != null ? "keyword='" + ViewBag.keyword + "'" : "")>
                <a class="page-link">@i</a>
            </li>
        }
    </ul>
</div>
<script>
    // Thêm script ajax cho click vào page-item, nút search
    $('body').on('click', '.li.page-item', function (e) {
        var page = $(this).attr("page");
        var mid = $(this).attr("mid");
        var keyword = $(this).attr("keyword");
        var data = { mid: mid, keyword: keyword, pageIndex: page };
        $.ajax({
            url: "LearnerFilter",
            data: data,
            success: function (response) {
                $("#div#content").html(response);
            }
        });
    });

    $(".nav li").click(function (e) {
        var id = $(this).attr("id");
        var data = { mid: id };
        $.ajax({
            url: "LearnerFilter",
            data: data,
            success: function (response) {
                $("#div#content").html(response);
            }
        });
    });

    $("#button#btnSearch").click(function (e) {
        var keyword = $("#keyword").val();
        var data = { keyword: keyword };
        $.ajax({
            url: "LearnerFilter",
            data: data,
            success: function (response) {
                $("#div#content").html(response);
            }
        });
    });
</script>

DAY15/DAY13_1/Views/Learners/LearnerTable.cshtml
@model IEnumerable<Learner>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Mã</th>
            <th>Tên</th>
            <th>Họ</th>
            <th>Ngành</th>
            <th>Ngày Nhập Học</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td>@s.LearnerID</td>
                <td>@s.FirstMidName</td>
                <td>@s.LastName</td>
                <td>@s.Major.MajorName</td>
                <td>@s.EnrollmentDate</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@s.LearnerID">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@s.LearnerID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<ul class="pagination">
    @for (int i = 1; i <= ViewBag.pageNum; i++)
    {
        <li class="page-item" page="@i"
            @(ViewBag.mid != null ? "mid='" + ViewBag.mid + "'" : "")
            @(ViewBag.keyword != null ? "keyword='" + ViewBag.keyword + "'" : "")>
            <a class="page-link">@i</a>
        </li>
    }
</ul>